# Minimal, safe starter
knowledge_base:
  repositories:
    - sw5e-foundry/dnd5e5.1.x
    - sw5e-foundry/foundryvtt13.1
    # Optional, only if private and legal to reference:
    # - my-org/foundry-core-mirror

