name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Format YAML (keys sorted) and Prettier
        run: |
          npm run fmt:yaml
          npm run fmt:prettier

      - name: Clean pack sources
        run: npm run build:clean

      - name: Fail if formatting/cleaning produced changes
        run: git diff --exit-code

      - name: Compile packs (sanity build)
        run: npm run build:db
